- name: Packagist Publish
  uses: wscourge/gha-packagist-publish@1.0.2
  with:
  username: "skploft"
  api_token: ${{ secrets.packagist_token }}
  #package_name: vendor/name # No need to be explicit if you have checked out a composer.json
  #domain: "packagist.org" # This is by default, so no need to specify this.