name: Packagist Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Packagist Publish
        uses: wscourge/gha-packagist-publish@1.0.2
        with:
          username: "skploft"
          api_token: ${{ secrets.packagist_token }}
